In [2]:
from skimage import io

image = io.imread('image_files/0000.jpg')

In [6]:
from skimage.color import rgb2gray
from skimage.filters import threshold_otsu
import numpy as np

gray_image = rgb2gray(image)

# Example for extracting a mask for a specific color
mask_color = np.all(image == [0, 255, 0], axis=-1)  # Replace r, g, b with the RGB values of the color


In [7]:
from skimage import img_as_ubyte

io.imsave('mask_1.png', img_as_ubyte(mask_color))

/var/folders/74/9tpvyg253_d1_06tsh3c83900000gn/T/ipykernel_42266/2622380087.py:3: UserWarning: mask_1.png is a low contrast image
  io.imsave('mask_1.png', img_as_ubyte(mask_color))


In [16]:
from PIL import Image
import numpy as np 

img = Image.open("frame_3885.jpg")
numpy_array = np.array(img)
print(numpy_array.shape)

(540, 960)


In [19]:
numpy_array = numpy_array.flatten()
numpy_array.shape

(518400,)

In [21]:
%pip install matplotlib


  Using cached matplotlib-3.8.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.8 kB)
  Using cached contourpy-1.2.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.8 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.4/159.4 kB 7.8 MB/s eta 0:00:00
  Using cached kiwisolver-1.4.5-cp310-cp310-macosx_11_0_arm64.whl.metadata (6.4 kB)
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Using cached matplotlib-3.8.3-cp310-cp310-macosx_11_0_arm64.whl (7.5 MB)
Using cached contourpy-1.2.0-cp310-cp310-macosx_11_0_arm64.whl (242 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 25.9 MB/s eta 0:00:00a 0:00:01
Using cached kiwisolver-1.4.5-cp310-cp310-macosx_11_0_arm64.whl (66 kB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
Note: you may need to restart the kernel to use updated packages.


In [22]:
import matplotlib.pyplot as plt

In [20]:

np.histogram(numpy_array,bins=34)

(array([398702,   3876,   1456,    675,   1108,    445,   3592,    357,
           164,    665,   5077,   1129,   1096,  16128,  14604,  16614,
          3735,   8055,   1016,   5664,   7168,   1021,   4069,    624,
           415,    478,  16758,    569,   2792,    198,     88,     41,
            13,      8]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
        26., 27., 28., 29., 30., 31., 32., 33., 34.]))

In [23]:
from PIL import Image
import numpy as np 

img = Image.open("frame_0.jpg")
numpy_array = np.array(img)
print(numpy_array.shape)

(540, 960)


In [24]:
numpy_array = numpy_array.flatten()
numpy_array.shape

(518400,)

In [29]:

np.histogram(numpy_array,bins=36)

(array([307809,   8809,   3023,   1387,   2382,   4450,   2327,  12811,
         13832,   2224,   6161,   3836,   3721,  15589,  24646,  23258,
          8176,  16018,   4979,   6633,   2893,   1529,   3597,   1611,
          1160,   2919,   2070,   1413,  25442,   3003,    389,    193,
            66,     36,      5,      3]),
 array([ 0.        ,  0.97222222,  1.94444444,  2.91666667,  3.88888889,
         4.86111111,  5.83333333,  6.80555556,  7.77777778,  8.75      ,
         9.72222222, 10.69444444, 11.66666667, 12.63888889, 13.61111111,
        14.58333333, 15.55555556, 16.52777778, 17.5       , 18.47222222,
        19.44444444, 20.41666667, 21.38888889, 22.36111111, 23.33333333,
        24.30555556, 25.27777778, 26.25      , 27.22222222, 28.19444444,
        29.16666667, 30.13888889, 31.11111111, 32.08333333, 33.05555556,
        34.02777778, 35.        ]))

In [28]:
len(np.unique(numpy_array))


36

In [39]:
new_array = np.histogram(numpy_array,bins=36)[0]
new_array

array([307809,   8809,   3023,   1387,   2382,   4450,   2327,  12811,
        13832,   2224,   6161,   3836,   3721,  15589,  24646,  23258,
         8176,  16018,   4979,   6633,   2893,   1529,   3597,   1611,
         1160,   2919,   2070,   1413,  25442,   3003,    389,    193,
           66,     36,      5,      3])

In [40]:
new_array=np.divide(new_array,518400)
new_array= np.multiply(new_array,100)
new_array

array([5.93767361e+01, 1.69926698e+00, 5.83140432e-01, 2.67554012e-01,
       4.59490741e-01, 8.58410494e-01, 4.48881173e-01, 2.47125772e+00,
       2.66820988e+00, 4.29012346e-01, 1.18846451e+00, 7.39969136e-01,
       7.17785494e-01, 3.00713735e+00, 4.75424383e+00, 4.48649691e+00,
       1.57716049e+00, 3.08989198e+00, 9.60455247e-01, 1.27951389e+00,
       5.58063272e-01, 2.94945988e-01, 6.93865741e-01, 3.10763889e-01,
       2.23765432e-01, 5.63078704e-01, 3.99305556e-01, 2.72569444e-01,
       4.90779321e+00, 5.79282407e-01, 7.50385802e-02, 3.72299383e-02,
       1.27314815e-02, 6.94444444e-03, 9.64506173e-04, 5.78703704e-04])

In [ ]:
from PIL import Image
import numpy as np 

img = Image.open("frame_0.jpg")
numpy_array = np.array(img)
print(numpy_array.shape)

In [48]:
def populaton_percentage_array(image_path:str):
    img = Image.open(image_path)
    numpy_array=np.array(img)
    numpy_array = numpy_array.flatten()
    size = numpy_array.shape[0]
    n_bins=len(np.unique(numpy_array))
    new_array = np.histogram(numpy_array,bins=n_bins)[0]
    new_array=np.divide(new_array,size)
    array_test= np.multiply(new_array,100)
    array_test = array_test[array_test>2e-01]
    return (len(array_test))

In [49]:
array_test=populaton_percentage_array('frame_3885.jpg')

In [52]:
array_test = array_test[array_test>2e-01]
array_test

array([76.91010802,  0.74768519,  0.2808642 ,  0.21373457,  0.69290123,
        0.97935957,  0.21778549,  0.21141975,  3.11111111,  2.81712963,
        3.20486111,  0.72048611,  1.55381944,  1.09259259,  1.38271605,
        0.78491512,  3.23263889,  0.53858025])

In [53]:
print(len(array_test))

18
